# 1.Melihat Data hasil Convert_Whatsapp.py

In [2]:
import pandas as pd
data = pd.read_csv('wa_guyup_rukun_sak_lawase.csv')
print("banyak data:", data.shape[0], ", kolom/fitur:", data.shape[1])

banyak data: 4316 , kolom/fitur: 4

In [3]:
data.head(10)

,Date,Time,Sender/Info,Message
0,8/16/21,08:19,Messages and calls are end-to-end encrypted. N...,NaN
1,1/13/17,19:31,"Pak Supri RT created group """"Guyup Rukun Sak l...",NaN
2,8/16/21,08:19,~ Sriyono added you,NaN
3,8/16/21,08:38,Pak Dwiyono,Inggih pak.
4,8/18/21,09:03,+62 813-2629-9837,Sugeng enjing pak RT kaliyan Pak RW nyuwun tul...
5,8/18/21,09:03,+62 813-2629-9837,<Media omitted>
6,8/18/21,09:34,+62 852-0023-9558,maturnuwun pak impormasinipun.🙏
7,8/18/21,09:37,+62 813-2629-9837,nggeh mas
8,8/18/21,10:15,+62 857-4056-6853,This message was deleted
9,8/24/21,19:45,+62 852-9335-6100,<Media omitted>

# 2.Melihat Data Hasil Get_Message_Only.py

In [6]:
data_msg = pd.read_csv('wa_guyup_rukun_sak_lawase_msg.csv')
print("banyak data:", data_msg.shape[0], ", kolom/fitur:", data_msg.shape[1])

banyak data: 4316 , kolom/fitur: 1

In [7]:
data_msg.head(10)

                                             Message
0                                                NaN
1                                                NaN
2                                                NaN
3                                        Inggih pak.
4  Sugeng enjing pak RT kaliyan Pak RW nyuwun tul...
5                                    <Media omitted>
6                    maturnuwun pak impormasinipun.🙏
7                                          nggeh mas
8                           This message was deleted
9                                    <Media omitted>

# 3.Melihat Data Hasil Clean_Whatsapp_CSV.py

In [10]:
data_clean = pd.read_csv('wa_guyup_rukun_sak_lawase_clean.csv')
print("banyak data:", data_clean.shape[0], ", kolom/fitur:", data_clean.shape[1])

banyak data: 3464 , kolom/fitur: 1

In [11]:
data_clean.head(10)

                                             Message
0                                        Inggih pak.
1  Sugeng enjing pak RT kaliyan Pak RW nyuwun tul...
2                     maturnuwun pak impormasinipun.
3                                          nggeh mas
4                           This message was deleted
5                                      Pelaksanaan :
6                          Hari.    : Kamis, 26/8/21
7                             Jam.   : 10.30 - 11.30
8                 Tempat : Aula balai ds Karangwungu
9  penyerahan santunan kangge adik valen saking P...